function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Factorial_StateFlow"};
	this.sidHashMap["Factorial_StateFlow"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Factorial_StateFlow:1"};
	this.sidHashMap["Factorial_StateFlow:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Factorial_StateFlow:8"};
	this.sidHashMap["Factorial_StateFlow:8"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "Factorial_StateFlow:1"};
	this.sidHashMap["Factorial_StateFlow:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Result"] = {sid: "Factorial_StateFlow:7"};
	this.sidHashMap["Factorial_StateFlow:7"] = {rtwname: "<Root>/Result"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "Factorial_StateFlow:1:1"};
	this.sidHashMap["Factorial_StateFlow:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "Factorial_StateFlow:1:2"};
	this.sidHashMap["Factorial_StateFlow:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "Factorial_StateFlow:1:3"};
	this.sidHashMap["Factorial_StateFlow:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "Factorial_StateFlow:1:4"};
	this.sidHashMap["Factorial_StateFlow:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "Factorial_StateFlow:1:5"};
	this.sidHashMap["Factorial_StateFlow:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "Factorial_StateFlow:1:6"};
	this.sidHashMap["Factorial_StateFlow:1:6"] = {rtwname: "<S1>:6"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
