function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Traffic_Light_StateFlow"};
	this.sidHashMap["Traffic_Light_StateFlow"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Traffic_Light_StateFlow:1"};
	this.sidHashMap["Traffic_Light_StateFlow:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "Traffic_Light_StateFlow:4"};
	this.sidHashMap["Traffic_Light_StateFlow:4"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "Traffic_Light_StateFlow:1"};
	this.sidHashMap["Traffic_Light_StateFlow:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<S1>:29"] = {sid: "Traffic_Light_StateFlow:1:29"};
	this.sidHashMap["Traffic_Light_StateFlow:1:29"] = {rtwname: "<S1>:29"};
	this.rtwnameHashMap["<S1>:16"] = {sid: "Traffic_Light_StateFlow:1:16"};
	this.sidHashMap["Traffic_Light_StateFlow:1:16"] = {rtwname: "<S1>:16"};
	this.rtwnameHashMap["<S1>:32"] = {sid: "Traffic_Light_StateFlow:1:32"};
	this.sidHashMap["Traffic_Light_StateFlow:1:32"] = {rtwname: "<S1>:32"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "Traffic_Light_StateFlow:1:1"};
	this.sidHashMap["Traffic_Light_StateFlow:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "Traffic_Light_StateFlow:1:6"};
	this.sidHashMap["Traffic_Light_StateFlow:1:6"] = {rtwname: "<S1>:6"};
	this.rtwnameHashMap["<S1>:30"] = {sid: "Traffic_Light_StateFlow:1:30"};
	this.sidHashMap["Traffic_Light_StateFlow:1:30"] = {rtwname: "<S1>:30"};
	this.rtwnameHashMap["<S1>:36"] = {sid: "Traffic_Light_StateFlow:1:36"};
	this.sidHashMap["Traffic_Light_StateFlow:1:36"] = {rtwname: "<S1>:36"};
	this.rtwnameHashMap["<S1>:34"] = {sid: "Traffic_Light_StateFlow:1:34"};
	this.sidHashMap["Traffic_Light_StateFlow:1:34"] = {rtwname: "<S1>:34"};
	this.rtwnameHashMap["<S1>:37"] = {sid: "Traffic_Light_StateFlow:1:37"};
	this.sidHashMap["Traffic_Light_StateFlow:1:37"] = {rtwname: "<S1>:37"};
	this.rtwnameHashMap["<S1>:40"] = {sid: "Traffic_Light_StateFlow:1:40"};
	this.sidHashMap["Traffic_Light_StateFlow:1:40"] = {rtwname: "<S1>:40"};
	this.rtwnameHashMap["<S1>:39"] = {sid: "Traffic_Light_StateFlow:1:39"};
	this.sidHashMap["Traffic_Light_StateFlow:1:39"] = {rtwname: "<S1>:39"};
	this.rtwnameHashMap["<S1>:38"] = {sid: "Traffic_Light_StateFlow:1:38"};
	this.sidHashMap["Traffic_Light_StateFlow:1:38"] = {rtwname: "<S1>:38"};
	this.rtwnameHashMap["<S1>:8"] = {sid: "Traffic_Light_StateFlow:1:8"};
	this.sidHashMap["Traffic_Light_StateFlow:1:8"] = {rtwname: "<S1>:8"};
	this.rtwnameHashMap["<S1>:15"] = {sid: "Traffic_Light_StateFlow:1:15"};
	this.sidHashMap["Traffic_Light_StateFlow:1:15"] = {rtwname: "<S1>:15"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
