function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Alarm_System"};
	this.sidHashMap["Alarm_System"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Alarm_System:27"};
	this.sidHashMap["Alarm_System:27"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Alarm_System:26"};
	this.sidHashMap["Alarm_System:26"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/ADC Value & LEDs"] = {sid: "Alarm_System:27"};
	this.sidHashMap["Alarm_System:27"] = {rtwname: "<Root>/ADC Value & LEDs"};
	this.rtwnameHashMap["<Root>/Swtich State"] = {sid: "Alarm_System:26"};
	this.sidHashMap["Alarm_System:26"] = {rtwname: "<Root>/Swtich State"};
	this.rtwnameHashMap["<S1>:88"] = {sid: "Alarm_System:27:88"};
	this.sidHashMap["Alarm_System:27:88"] = {rtwname: "<S1>:88"};
	this.rtwnameHashMap["<S1>:89"] = {sid: "Alarm_System:27:89"};
	this.sidHashMap["Alarm_System:27:89"] = {rtwname: "<S1>:89"};
	this.rtwnameHashMap["<S1>:123"] = {sid: "Alarm_System:27:123"};
	this.sidHashMap["Alarm_System:27:123"] = {rtwname: "<S1>:123"};
	this.rtwnameHashMap["<S1>:122"] = {sid: "Alarm_System:27:122"};
	this.sidHashMap["Alarm_System:27:122"] = {rtwname: "<S1>:122"};
	this.rtwnameHashMap["<S1>:124"] = {sid: "Alarm_System:27:124"};
	this.sidHashMap["Alarm_System:27:124"] = {rtwname: "<S1>:124"};
	this.rtwnameHashMap["<S1>:125"] = {sid: "Alarm_System:27:125"};
	this.sidHashMap["Alarm_System:27:125"] = {rtwname: "<S1>:125"};
	this.rtwnameHashMap["<S1>:128"] = {sid: "Alarm_System:27:128"};
	this.sidHashMap["Alarm_System:27:128"] = {rtwname: "<S1>:128"};
	this.rtwnameHashMap["<S1>:129"] = {sid: "Alarm_System:27:129"};
	this.sidHashMap["Alarm_System:27:129"] = {rtwname: "<S1>:129"};
	this.rtwnameHashMap["<S2>:180"] = {sid: "Alarm_System:26:180"};
	this.sidHashMap["Alarm_System:26:180"] = {rtwname: "<S2>:180"};
	this.rtwnameHashMap["<S2>:176"] = {sid: "Alarm_System:26:176"};
	this.sidHashMap["Alarm_System:26:176"] = {rtwname: "<S2>:176"};
	this.rtwnameHashMap["<S2>:182"] = {sid: "Alarm_System:26:182"};
	this.sidHashMap["Alarm_System:26:182"] = {rtwname: "<S2>:182"};
	this.rtwnameHashMap["<S2>:177"] = {sid: "Alarm_System:26:177"};
	this.sidHashMap["Alarm_System:26:177"] = {rtwname: "<S2>:177"};
	this.rtwnameHashMap["<S2>:181"] = {sid: "Alarm_System:26:181"};
	this.sidHashMap["Alarm_System:26:181"] = {rtwname: "<S2>:181"};
	this.rtwnameHashMap["<S2>:175"] = {sid: "Alarm_System:26:175"};
	this.sidHashMap["Alarm_System:26:175"] = {rtwname: "<S2>:175"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
